### ISSUE TITLE
Problem with cov-combine

### ISSUE THREAD

**Issue by Mirazoqui** [edgraham/BinSanity#1]
I've tried to run cov-combine, but it kept giving the same error message: 

$ python cov-combine.py -c coverage -o Combined.coverage
  File "cov-combine.py", line 74
    elif 
        ^
SyntaxError: invalid syntax

This is the line 74: 
    if args.inputoutput is None:
        parser.error('-o output fasta file needed')
    if args.inputCoverage is None:
        parser.error('-c suffic linking coverage profiles needed')
    elif 
        
    else:
        time = time.time()

It looked odd to have an empty "elif", but I'm not really familiarized with python. I was wondering if it was my mistake or it's something with the code. Thanks so much

**Comment by edgraham** [comment]
Hi Mirazoqui,

My apologies for that, at some point when transitioning between versions that 'elif' statement escaped removal. I removed that from the cov-combine script
Please let me know if you have any subsequent issues, I am actively working on improving and developing the scripts associated with Binsanity to optimize performance.
