### ISSUE TITLE
I/O Error with shutil.py

### ISSUE THREAD

**Issue by seanmcallister** [edgraham/BinSanity#10]
Command called:

```
Binsanity-wf -c S1_binsanity.cov.x100.lognorm -f ./ -l S1_simplifiedheaders.fasta -x 2000 --threads 16
```

When running, the program works fine through the first round of binning and CheckM results then dies with this error:

```
Traceback (most recent call last):
  File "/home/mcallis/software/BinSanity/bin/Binsanity-wf", line 429, in <module>
    shutil.copyfileobj(readfile,outfile)
  File "/usr/lib64/python2.7/shutil.py", line 52, in copyfileobj
    fdst.write(buf)
ValueError: I/O operation on closed file
```

I'm not sure, but I think it might be because the "outfile" has been closed in the previous lines.

```
with open("low_completion.fna","wb") as outfile:
            for filename in glob.glob(str(location2)+"/*.fna"):
                if filename == "low_completion.fna":
                    continue
        with open(filename,"rb") as readfile:
            shutil.copyfileobj(readfile,outfile)
            shutil.move("low_completion.fna", str(location))
            shutil.rmtree(str(location2))

```

Please let me know if I'm just missing something. I'm using python 2.7.11.

**Comment by seanmcallister** [comment]
Update:
I installed python 2.7.6 and ran it again with the same error.

**Comment by edgraham** [comment]
Hello,

My apologies, I wasn't able to get to this until today. I went through the code base and the issue should be resolved. You'll need to update via either pip or from the code base here. The issue was due to an identation error in the last update.

please let me know if you continue to have issues running it!

Regards,
Elaina Graham
