### ISSUE TITLE
low_completion.fna errors

### ISSUE THREAD

**Issue by seanmcallister** [edgraham/BinSanity#11]
Command line for Binsanity-wf v0.2.5.4:

```
Binsanity-wf -c S6_binsanity.cov.x100.lognorm -f ./ -l S6_simplifiedheaders.fasta -x 2000 --threads 20
```

After doing the initial binning and all of the refinement, the program exits when it attempts to process the low_completion.fna file. I think earlier you try to move it out of the Redundant Bins folder, but in my case, that file is still in the folder.

Here is the exit warning:

```
            -------------------------------------------------------
                       Reclustering redundant bin low_completion.fna
            -------------------------------------------------------
Preference: -25
Maximum Iterations: 4000
Convergence Iterations: 400
Contig Cut-Off: 2000
Damping Factor: 0.95
Coverage File: S6_binsanity.cov.x100.lognorm
Fasta File: low_completion.fna
Traceback (most recent call last):
  File "/home/mcallis/software/BinSanity/bin/Binsanity-wf", line 466, in <module>
    val1, val2 = cov_array((get_cov_data('tetra-GC-out')), location, redundant_bin,args.ContigSize)
  File "/home/mcallis/software/BinSanity/bin/Binsanity-wf", line 49, in cov_array
    print cov_array.shape
AttributeError: 'list' object has no attribute 'shape'
```

Looking at the script, it seems like there isn't anything left in the workflow except some moving of files, so I should be ok without a rerun, right? Thanks!

**Comment by seanmcallister** [comment]
Update: The low_completion.fna file was empty, which is the reason that the program threw the error. Perhaps a check before attempting Binsanity-refine on the file would fix the problem. Thanks!

**Comment by edgraham** [comment]
Hi Sean,

Thanks for all your comments recently, I am in the process of working up a full program update for BinSanity (including a Python3 transition), so my apologies for delayed responses recently!

The original `Binsanity-wf` codebase assumed there would always be something in the low_completion file, which in most cases is true, but if the sample diversity is low or there are many organisms with a similar abundance profile across two or more samples then you'll certainly find a situation in which all the clusters end up being high redundancy prior to refinement (as with your case). This fix will be rolled in with the next major update in a couple days as I finish testing the new codebase.

Regards,
Elaina Graham
