### ISSUE TITLE
Binsanity-wf fails

### ISSUE THREAD

**Issue by dparks1134** [edgraham/BinSanity#13]
Hello,

I am trying to run the "Binsanity-wf" command as follows:
`Binsanity-wf -f <my_assembly_dir> -l <my_assembly> -c binsanity.profile.cov.x100.lognorm -o output --threads 20`

This successfully runs the Binsanity and CheckM, but then immediately fails after CheckM:

```
*******************************************************************************
 [CheckM - qa] Tabulating genome statistics.
*******************************************************************************

  Calculating AAI between multi-copy marker genes.

  Reading HMM info from file.
  Parsing HMM hits to marker genes:
    Finished parsing hits for 10 of 10 (100.00%) bins.

  { Current stage: 0:00:06.542 || Total: 0:06:01.380 }
Traceback (most recent call last):
  File "/gnu/store/vzmhc8h9i20as615l0lmbnjqb3lww85s-binsanity-0.2.5.5/bin/..Binsanity-wf-real-real", line 429, in <module>
    shutil.copyfileobj(readfile,outfile)
  File "/srv/sw/python/2.7.4/lib/python2.7/shutil.py", line 52, in copyfileobj
    fdst.write(buf)
ValueError: I/O operation on closed file
```

Do you have any insights into what might be causing this issue?

**Comment by edgraham** [comment]
Hi Donovan,

Can you send me the version of BinSanity you are running?

Regards,
Elaina Graham

**Comment by dparks1134** [comment]
I'm running v0.2.5.5.

**Comment by edgraham** [comment]
Hi Donovan,

Thanks for the information. Try updating the version to v0.2.5.9. I think
this may be an issue that occured when I was updated version between
v0.2.5.4 and v0.2.5.5 where I accidently closed a file I was writing to in
python before BinSanity was finished using it. I fixed it in the subsequent
versions.

If that doesn't solve it please let me know!

Regards,
Elaina

**Comment by dparks1134** [comment]
Yep, that solved the issue. Thanks.
