### ISSUE TITLE
binsanity-checkm created in current working directory

### ISSUE THREAD

**Issue by dparks1134** [edgraham/BinSanity#15]
Hello,

I'm using BinSanity v0.2.5.9 and have encountered a small issue. When running the program it creates the directory 'binsanity-checkm' in the current working directory. As a consequence, if another instance o f BinSanity is run in the same directory it will fail as this directory will already exist. Would it be possible to give this directory a unique/temporary name in order to avoid this conflict? I often run binning methods in parallel over multiple independent samples so this situation is problematic. 

Thanks,
Donovan

**Comment by edgraham** [comment]
Hi Donovan, 

I updated Binsanity-wf and Binsanity-lc with a new flag to make running things in paralell in the same directory possible. There is now a `--Prefix` flag that can be invoked and whatever prefix you specify will be appended to the all of the directories, logfiles, etc. that BinSanity produces throughout. 

Regards,
Elaina
