### ISSUE TITLE
please provide release tag

### ISSUE THREAD

**Issue by EricDeveaud** [edgraham/BinSanity#17]
Hello, 

would it be possible to tag a release.

our policy is to install tagged release versions

thanks 

Eric

**Comment by edgraham** [comment]
Hi Eric,

I can certainly start doing that. I am working on some minor cosmetic updates to the codebase now so and can start tagging all my releases from this one onward.

Regards,
Elaina

**Comment by edgraham** [comment]
Our newest version has been tagged!
