### ISSUE TITLE
cov_array Error: 'list' object has no attribute 'shape'

### ISSUE THREAD

**Issue by palomo11** [edgraham/BinSanity#20]
Hi,

I'm running Binsanity-wf. Everything was going fine but now it has called for an error.

So far the folders and files created are:

BinSanityWf_binsanity_checkm
BinSanityWf_checkm_lineagewf-results.txt
BINSANITY-INITIAL
BinSanityWf_GC_count.txt
BinSanityWf_4mer_frequencies.txt
BinSanityWf_kmerGC.txt
BinSanityWf.log

But BinSanityWf_kmerGC.txt is empty.

Checking the log files it stopped at this moment:

Creating Profile for                     
                          redundant bin low_completion.fna                         
             ______________________________________________________
          Combined profile created in 2.07199311256 seconds
 
             ______________________________________________________ 
	                                                           
               Reclustering redundant bin low_completion.fna                       
             ______________________________________________________
          Preference: -25
          Maximum Iterations: 4000
          Convergence Iterations: 400
          Contig Cut-Off: 1000
          Damping Factor: 0.95
          Coverage File: depth_WW_binsanity_50000.cov.x100.lognorm_OK
          Fasta File: low_completion.fna
          Kmer: 4

The error file says:

/services/tools/anaconda-2.2.0/lib/python2.7/site-packages/Bio/Seq.py:155: BiopythonWarning: Biopython Seq objects now use string comparison. Older versions of Biopython used object comparison. During this transition, please use hash(id(my_seq)) or my_dict[id(my_seq)] if you want the old behaviour, or use hash(str(my_seq)) or my_dict[str(my_seq)] for the new string hashing behaviour.
  "the new string hashing behaviour.", BiopythonWarning)
Traceback (most recent call last):
  File "/services/tools/anaconda-2.2.0/bin/Binsanity-wf", line 477, in <module>
    val1, val2 = cov_array((get_cov_data(os.path.join(args.outputdir,str(args.prefix)+'_kmerGC.txt'))), location, redundant_bin,args.ContigSize)
  File "/services/tools/anaconda-2.2.0/bin/Binsanity-wf", line 50, in cov_array
    print "          %s" % (cov_array.shape,)
AttributeError: 'list' object has no attribute 'shape'

Any idea how to solve this problem?

Thanks in advance.

**Comment by edgraham** [comment]
Hello,

Can you send me the version of all BinSanity dependencies your running, as
well as the first few lines of your coverage file?

Regards,
Elaina

**Comment by palomo11** [comment]
Python (v2.7.12)
Numpy (v1.13.3)
SciKit (v0.19.1)
Biopython (v1.70)
BedTools (v2.17.0)
Pandas (v0.21.1)

Hmmer(v3.1b2)
Bedtools(v2.26.0)

I'm not sure about FeatureCounts, but it is not use during Binsanity-wf, right?

First few lines of coverage file (In bold the contig name):
**340**	2.40289387362	1.17965805393	1.46915607819	2.56123379941	0.820679511534	0.986610970784	1.44202328486	2.26876044954	2.37663352114	2.28336908192	2.21301277881	2.40528829097	1.96685761092	2.09731632252	2.166504118191.78410210933	2.40328013369	2.17912360477	2.24998304823	3.31205035118	1.25445622994	2.47982570944	2.09606492284	2.20070279097
**815**	1.97758003581	2.34105051372	2.10077018785	1.94221795265	2.06406844711	2.01928249576	2.72808175544	1.92566165584	1.13671105695	2.89874053516	2.70262092939	1.69663505171	2.47342565357	1.85640742977	1.863547683172.35824521853	2.06008940207	2.05889650829	1.97254439841	2.05174276167	2.0765202953	2.68210173505	2.13970596352	2.21728122615
**1806**	3.45525457972	2.4230245732	0.428863408299	1.59375777364	0.942571525649	0.84850563618	0.330034107125	3.16840613654	0.634249482933	1.1992284404	1.8993153551	2.13618450092	0.723358786467	1.87240104092	0.615474486030.851479109936	0.849578482641	1.11761262967	0.678445535282	1.20823706099	0.746153718739	2.24280470783	1.30732271341	0.313143496289

**Comment by palomo11** [comment]
I run Binsanity-wf with the example data and it worked fine.

Then, I focused on what was different between my data and the example data. The main different was that my contigs names were numerical. I have changed that (i.e from >1 to >contig-1) both in the contig file and in the coverage file and now it works fine. 

Maybe you could add a note about this in the home page of Binsanity.

Best regards.

**Comment by edgraham** [comment]
Hello,

That is an interesting finding. I am running through some iterations of why
this might be occuring, in the mean time I will add this to the github page
so people are aware!

Thank you!
