### ISSUE TITLE
Thoughts on using binsanity on data sets that have been MDA'd

### ISSUE THREAD

**Issue by JackieGOO** [edgraham/BinSanity#24]
What are your thoughts on the use of binsanity for binning from metagenomes where MDA was performed on the DNA?  ( MDA is notorious for uneven coverage)

**Comment by edgraham** [comment]
Hello Jackie,

If you have used MDA avoid using any methods that incorporate coverage. Focus on using compositional metrics like tetranucleotides or GC%. The uneven coverage would be a seriosu issue for BinSanity's current implementation. 

My advice would be to take your metagenomes, cluster only using the compositional metrics, and then do some manual refining in Anvi'o. I highly encourage the manual refinment! 

Hope that helps!
