### ISSUE TITLE
Test produces no bins

### ISSUE THREAD

**Issue by sturne29** [edgraham/BinSanity#25]
Hello!

I tried installing BinSanity (on the cluster I have access to, where most of the dependencies are available as modules; I installed pandas and featureCounts myself) and used the provided igm.fa and Infant_gut_assembly.cov.x100.lognorm files provided to test the installation, following the guide in the  instructions. Everything seemed to go as planned, but instead of getting the 22-bin output, I got 0 bins and 4188 clusters. I'm assuming I'm missing a dependency/a dependency did not act as expected, but I'm not sure what it would be. Any help would be appreciated.

To be clear: the "Computing Coverage Array" part was as expected, but the "Clustering Contigs" part was not.

Thanks!

**Comment by transcript** [comment]
Just want to comment that I've found the same issue occurs.  This is running on Ubuntu 14.04, 0 bins, 4188 clusters.

**Comment by edgraham** [comment]
Hi Guys,

I’ll look into this ASAP. I’m
Currently in the field though so internet is a bit dodgy so it might take me a bit longer than usual to address.

Regards,
Elaina

**Comment by edgraham** [comment]
Can you both send me the commands you used to run BinSanity as well as your version for scipy/sklearn?

**Comment by sturne29** [comment]
Sure!

> Binsanity -f . -l /path/to/igm.fa -p -10 -c /path/to/Infant_gut_assembly.cov.x100.lognorm

It was identical to the command in the test section of the Installation page on the wiki, except for the paths to the infant gut contigs and coverage profile.

SciPy: 0.18.0
Sklearn: 0.17.1

**Comment by edgraham** [comment]
I can't seem to get this to replicate on my computer :/

So lets approach this different. Here are the versions of everything I am running related to BinSanity (a couple are updated compared to whats on the wiki currently):

Python 2.7.14
Numpy 1.14.0
sklearn: 0.19.1
scipy: 0.19.1
biopython: 1.70
Pandas: 0.22.0
CheckM: 1.0.11

Next if all of that checks double check the FASTA file and coverage profile to make sure they appear to have downloaded in the right format. 

You can also test running Binsanity with these parameters: 

Binsanity -f . -l /path/to/igm.fa -p -25 -c /path/to/Infant_gut_assembly.cov.x100.lognorm

Reducing the preference should lead to more clumping. Whatever result you get will help point me in the direction of what needs to be fixed.

**Comment by sturne29** [comment]
Sorry for the late reply, I was out on a research vessel and didn't have access to the internet for a while. I'll go through and check out what you suggested, then report back.

**Comment by sturne29** [comment]
I installed an updated version of sklearn, and that seems to have done the trick - when I run the test command now, I get the expected output of 22 bins. (NB: I can't say for sure this is the thing that fixed it for me, but it's the only thing that I changed between my first attempts and now.) I hope this helps anyone else who has this issue!
