### ISSUE TITLE
Binsanity-lc: TypeError: unhashable type: 'numpy.ndarray'

### ISSUE THREAD

**Issue by acaciazhao** [edgraham/BinSanity#26]
Hi,

I got memory error when running Binsanity-wf so I tried Binsanity-lc. I kept getting this error. I installed Binsanity through pip install and it should be version 0.2.6.5. Any idea what might be causing it?

            ____________________________________________________

             Clustering Bin  BinSanityLC-kmean-bin_17.fna
             via Affinity Propagation
            ____________________________________________________

          Preference: -3
          Maximum Iterations: 4000
          Convergence Iterations: 400
          Contig Cut-Off: 1000
          Damping Factor: 0.95
          Coverage File: profile_output.cov
          Fasta File: BinSanityLC-kmean-bin_17.fna
          Output Directory: binsanity_bins
          (3666, 1)
Traceback (most recent call last):
  File "/slipstream/home/acacia/anaconda2/bin/Binsanity-lc", line 479, in <module>
    affinity_propagation(val3,val4,clust,args.damp,args.maxiter,args.conviter,args.preference,location_kmean,args.outputdir)
  File "/slipstream/home/acacia/anaconda2/bin/Binsanity-lc", line 64, in affinity_propagation
    outfile_data[apclust[i]] = [names[i]]
TypeError: unhashable type: 'numpy.ndarray'

**Comment by edgraham** [comment]
I’ll take a look at this today. What version of numpy are you running?

**Comment by acaciazhao** [comment]
Thanks. Numpy version is 1.14.5.

**Comment by edgraham** [comment]
Hello,

I haven't been able to recreate this, so maybe its an issue with the input array? Check your coverage profile as it seems to be failing when reading the coverage file into a numpy area. Occasionaly if you transfer things between a home computer and a server it may change the seperator type from a tab to something else and then numpy would have difficulty reading the file.

--Elaina
