### ISSUE TITLE
Output dir not used in Binsanity-profile

### ISSUE THREAD

**Issue by openpaul** [edgraham/BinSanity#27]
Hello,

as far as I can tell there is a bug in Binsanity-profile where the output folder is not used for the coverage profile:

```
    out1 = open(str(outfile)+".cov", "w")
```
Should be
```
    out1 = open(os.path.join(outputdir,str(outfile)+".cov"), "w")
```
If I understand the documentation correctly. 

This is a minor bug

**Comment by edgraham** [comment]
You are definitely correct, I’ll make the changes. Thanks for letting me know!
