### ISSUE TITLE
No log outputted.

### ISSUE THREAD

**Issue by kodragonP** [edgraham/BinSanity#28]
Hello,
As it is noticed that "BinSanity becomes highly memory intensive at 100,000 contigs or above", I have 2.5 million contigs, but only 2G memory were occupied using Binsanity command. Is it updated? By the way, no log was outputted. (the software was installed by bioconda)

**Comment by edgraham** [comment]
Hello,

We have not yet fixed the memory issue. Did the process output the
appropiate files? If you check the wiki
<https://github.com/edgraham/BinSanity/wiki/Usage> you can find what the
program should have output. If it didn't output all of those files in all
likelihood something failed to run properly. The next time you run it try
piping the stderr and stdout to a new file. Unfortunately it is difficult
to catch every error so it is possible that the program incurred an error
but proceeded to run without completing one or two steps along the way
which would ultimately skew your binning results.

I would also check your 2.5 million contigs, are most of them greater than
or less than 1000 bp. By default Binsanity ignored contigs less than
1000bp.

I'll make a not on the gitbhub to remind myself to look into adding an
error catching mechanism for memory issues.

-Elaina
