### ISSUE TITLE
Error in Binsanity-lc.cov_array() - 'list' object has no attribute 'shape'

### ISSUE THREAD

**Issue by prehensilecode** [edgraham/BinSanity#30]
Using:
* Binsanity-lc v0.2.7
* Python 2.7.13 (from Intel)

After some hours of running Binsanity-lc:

```
              Reclustering redundant bin BinSanityLC-kmean-bin_35-bin_59.fna
            ____________________________________________________
          Preference: -25
          Maximum Iterations: 4000
          Convergence Iterations: 400
          Contig Cut-Off: 1000
          Damping Factor: 0.95
          Coverage File: /lustre/Testing/fooGrp/CONDABINSAN/COVERAGE.cov
          Fasta File: BinSanityLC-kmean-bin_35-bin_59.fna
          Kmer: 4
Traceback (most recent call last):
  File "/home/juser/.local/bin/Binsanity-lc", line 564, in <module>
    val1, val2 = cov_array((get_cov_data(os.path.join(args.outputdir,args.prefix +'-kmerGC.txt'))), location, redundant_bin,args.ContigSize)                                 
  File "/home/juser/.local/bin/Binsanity-lc", line 51, in cov_array
    print "          %s" % (cov_array.shape,)
AttributeError: 'list' object has no attribute 'shape'
```

**Comment by prehensilecode** [comment]
Probably an issue with my data: the file `BinSanityLC-kmerGC.txt` in the output directory is empty.

**Comment by edgraham** [comment]
Hello,

Try the command on the example dataset and let me know if it runs. One other possibility is that if pandas or jumpy have been updated there may be an issue with compatibility that I need to address. It has happened in the past that the program had issues related to the most recent update of pandas where there was an issue based on the current code base.

-Elaina

**Comment by prehensilecode** [comment]
Tried again with different combination:
Binsanity-lc: v0.2.7
Python: 2.7.13 (Intel)
numpy: 1.12.1
pandas: 0.20.1

Completed successfully, but log was different. See attached.
[BinSanityLC-BinsanityLC-log.2.txt](https://github.com/edgraham/BinSanity/files/2716927/BinSanityLC-BinsanityLC-log.2.txt)
