### ISSUE TITLE
Empty List from Binsanity-profile

### ISSUE THREAD

**Issue by mbcouger** [edgraham/BinSanity#41]
Hello, 

When generating the cov profile using Binsanity-profile I get the error listed below, is this do to a dependency, I am using the most recent anaconda version

Many Thanks,
Brian

 Load annotation file TwentTo50Megahit.bam.saf ...                          ||
||    Features : 62038931                                                     ||
||    Meta-features : 62038931                                                ||
||    Chromosomes/contigs : 62038931                                          ||
||                                                                            ||
|| Process BAM file TwentTo50Megahit.bam...                                   ||
||    Paired-end reads are included.                                          ||
||    Assign alignments to features...                                        ||

        ******************************************************
                    Contigs formated to generate counts
        ******************************************************
        
Traceback (most recent call last):
  File "/home/couger/.conda/envs/purge_haplotigs_env/bin/Binsanity-profile", line 176, in <module>
    make_coverage(args.inputIds,args.outCov,args.outDirectory)
  File "/home/couger/.conda/envs/purge_haplotigs_env/bin/Binsanity-profile", line 60, in make_coverage
    contig_length = cov_data[k].pop(0)
IndexError: pop from empty list

**Comment by edgraham** [comment]
Hello,

It doesn’t appear to be a dependency. It looks like BinSanity profile is failing to populate a list somewhere. 

Does the program make it through the feature counts part of the script?

-Elaina

**Comment by mbcouger** [comment]
Hello Elaina, 

 I believe so, "it seems to run into the issue at contigs formated to generate counts" Here is the out log at this spot:

Load annotation file TwentTo50Megahit.bam.saf ...                          ||
||    Features : 62038931                                                     ||
||    Meta-features : 62038931                                                ||
||    Chromosomes/contigs : 62038931                                          ||
||                                                                            ||
|| Process BAM file TwentTo50Megahit.bam...                                   ||
||    Paired-end reads are included.                                          ||
||    Assign alignments to features...                                        ||

        ******************************************************
                    Contigs formated to generate counts

Traceback (most recent call last):
  File "/home/couger/.conda/envs/purge_haplotigs_env/bin/Binsanity-profile", line 176, in <module>
    make_coverage(args.inputIds,args.outCov,args.outDirectory)
  File "/home/couger/.conda/envs/purge_haplotigs_env/bin/Binsanity-profile", line 60, in make_coverage
    contig_length = cov_data[k].pop(0)
IndexError: pop from empty list


Many Thanks,
Brian

**Comment by edgraham** [comment]
Hi brian,

Sorry I took so long to reply. I can't seem to recreate this issue. Can you
send me all the version of the dependencies your running within conda? I
have had a few other comments related to this and I think it may be related
to the conda installation, I am working on my own conda repository, but the
one currently available via conda isn't one I personally packaged so there
may be a discrepancy in how conda installs one of the requirements.

Other things to check, make sure featureCounts is working properly by
running it outside of the program.

-Elaina
