### ISSUE TITLE
Binsanity-lc's TabError

### ISSUE THREAD

**Issue by iquasere** [edgraham/BinSanity#42]
Greetings. I installed Binsanity with pip, and when trying to run Binsanity for the first time, I get
```
File "/home/jsequeira/anaconda3/bin/Binsanity-lc", line 103
    contig_number = 0
                    ^
TabError: inconsistent use of tabs and spaces in indentation
```
Is the pip version up to date?

**Comment by edgraham** [comment]
Hello,

try updating to the newest pip version. It seems like it was an issue
associated with downloading from pip while using python3.

-Elaina
