### ISSUE TITLE
Release source code in PyPI

### ISSUE THREAD

**Issue by apcamargo** [edgraham/BinSanity#44]
Hi!

I want o update BinSanity's recipe in Bioconda baceuse the current one doesn't support Python 3. However, I've noticed that the the source code was not uploaded to PyPI, only the wheel.

Would it be possible to upload BinSanity's source to PyPI?

Thank you!

**Comment by edgraham** [comment]
Hello,

My apologies for that there must have been an issue with the last twine
update, I just re-uploaded a "new" version v0.3.4 that has the source
(since pypi won't let me alter the one thats currently there).

-Elaina

**Comment by apcamargo** [comment]
Thanks! Here's the PR for the recipe: https://github.com/bioconda/bioconda-recipes/pull/19964

I've removed `subread` and `sklearn` from the requirements because they weren't in `setup.py`. Is this ok?
