### ISSUE TITLE
utils scripts :: TabError: inconsistent use of tabs and spaces in indentation

### ISSUE THREAD

**Issue by EricDeveaud** [edgraham/BinSanity#50]
Hello, 

scripts form the utilsdirectory contains mixed tab and sapces as indentation.
that genrate an error
```
bin_evaluation
concat
get-ids
simplify-fasta
transform-coverage-profile
```

regards

Eric

**Comment by edgraham** [comment]
Those scripts hadn't yet been tested in python3 which is why you were getting the error. It is repaired now and they all work based on my tests.
