### ISSUE TITLE
Bio.Alphabet removed from Biopython

### ISSUE THREAD

**Issue by alxsimon** [edgraham/BinSanity#51]
There is an issue with the conda installation.

Removing the import works. Two solutions I think, dropping the use of Allphabet or fixing the version of Biopython used in the conda recipe.

For example when calling Binsanity-wf
```
Traceback (most recent call last):                                                             
  File "/opt/miniconda3/envs/binsanity/bin/Binsanity-wf", line 13, in <module>                 
    from Bio.Alphabet import IUPAC                                                             
  File "/opt/miniconda3/envs/binsanity/lib/python3.8/site-packages/Bio/Alphabet/__init__.py", l
ine 20, in <module>                                                                            
    raise ImportError(                                                                         
ImportError: Bio.Alphabet has been removed from Biopython. In many cases, the alphabet can simp
ly be ignored and removed from scripts. In a few cases, you may need to specify the ``molecule_
type`` as an annotation on a SeqRecord for your script to work correctly. Please see https://bi
opython.org/wiki/Alphabet for more information.                                                
```

**Comment by edgraham** [comment]
Hello,

I will look into this. It must specifically be a python3.8 issue. The
current tests for python3 have been in python3.6 and after testing today in
my own python3.6.11 conda env I am not getting this error. I will work to
deprecate this for future versions but for the time being creating a conda
env with python3.6 should solve this.

Regards,
Elaina Graham

**Comment by maherrl** [comment]
Hello,

I am getting the same error after creating a conda environment with python=3.6. 

```
conda create -n python3.6 python=3.6
conda activate python3.6
pip3 install BinSanity

(python3.6) [maherr@calculon ~]$ Binsanity-wf -f ../ -l co_contigs.fa -c cov_out.txt.cov.x100.lognorm -o binsanity-wf -x SizeThreshold 1500 --threads 10
Traceback (most recent call last):
  File "/nfs1/MICRO/Thurber_Lab/becca/opt/conda/envs/python3.6/bin/Binsanity-wf", line 13, in <module>
    from Bio.Alphabet import IUPAC
  File "/nfs1/MICRO/Thurber_Lab/becca/opt/conda/envs/python3.6/lib/python3.6/site-packages/Bio/Alphabet/__init__.py", line 21, in <module>
    "Bio.Alphabet has been removed from Biopython. In many cases, the alphabet can simply be ignored and removed from scripts. In a few cases, you may need to specify the ``molecule_type`` as an annotation on a SeqRecord for your script to work correctly. Please see https://biopython.org/wiki/Alphabet for more information."
ImportError: Bio.Alphabet has been removed from Biopython. In many cases, the alphabet can simply be ignored and removed from scripts. In a few cases, you may need to specify the ``molecule_type`` as an annotation on a SeqRecord for your script to work correctly. Please see https://biopython.org/wiki/Alphabet for more information.
(python3.6) [maherr@calculon ~]$ Binsanity --version
Binsanity v0.4.4
```
Not sure if I didn't set up the environment correctly, or if the issue has not yet been resolved.

Any suggestions?

Becca

**Comment by alxsimon** [comment]
I think I fixed my problem initially by setting a given version of Biopython in the [meta.yaml](https://github.com/edgraham/BinSanity/blob/master/conda-recipe/meta.yaml) file. But I do not remember exactly (forgot to note the steps I have taken once again...).

**Comment by Geize** [comment]
Hi Elaina, 

Do you have any tips for this? Or should I  create a new env py=3.6  to install everything again?

**Comment by edgraham** [comment]
Hi All,

I apologize for it taking me so long to respond to this, its been a busy past year. I will be pushing a new version out today that will fix this. I have also been working on a new version Binsanity2 that will be released this summer and I will push the beta version to the github with the updates for this today if anyone wants to use the updated version (the program itself works but needs to be streamlined prior to official release). 

In terms of the module in question after going through the code I found that the `Bio.Alphabet` had been deprecated out of the code already and the import statement was just a legacy feature. So you can also just delete that import statement from you local install and everything should work.

-Elaina

**Comment by edgraham** [comment]
This is now updated in a new version v0.5 on pypi and github. I will get
conda up soon.

**Comment by Geize** [comment]
Thanks Elaina. 

If you could update at the conda should be great. 

Thanks for your attention.

**Comment by edgraham** [comment]
Just in case you haven't checked it is updated in conda now.

**Comment by Geize** [comment]
Hi Elaina, 

Thanks for your update. 

FIY 

I removed Bio.Alphabet (as well IUPAC) from all script, used the  script you sent to reformat txt file, and then BinSanity (previous version) worked very well. 

Many thanks for your help. 

best,
