### ISSUE TITLE
I tried with carol's dataset and meren.cov but got errors.

### ISSUE THREAD

**Issue by liuxianghui** [edgraham/BinSanity#6]
-------------------------------------------------------
                          Running Binsanity

                    ---Computing Coverage Array ---
        -------------------------------------------------------

Preference: -10.0
Maximum Iterations: 4000
Convergence Iterations: 400
Contig Cut-Off: 1000
Damping Factor: 0.95
Coverage File: meren.cov
Fasta File: igm.fa
Output directory: BINSANITY-RESULTS
(4189, 11)

Total Number of Bins: 22
Traceback (most recent call last):
  File "/data/xianghui/cgat-python/bin/Binsanity", line 175, in <module>
    affinity_propagation(val1, val2, args.fastafile, args.damp, args.maxiter, args.conviter, args.preference,args.inputContigFiles,args.outputdir)
  File "/data/xianghui/cgat-python/bin/Binsanity", line 84, in affinity_propagation
    unbinned_file.close()
NameError: global name 'unbinned_file' is not defined
Mon Nov 28 11:04:22 SGT 2016

**Comment by liuxianghui** [comment]
Sorry. shall be Sharon's dataset.

**Comment by edgraham** [comment]
Hi liuxianghui,
Try updating with pip and check the script now. That was an issue from the deprecated version that got overlooked in transitioning between versions.

**Comment by rprops** [comment]
I encounter the same issue after updating to v0.2.1 (pip install Binsanity --upgrade --user).
![image](https://cloud.githubusercontent.com/assets/19682548/21438050/2c4cb814-c855-11e6-890a-5962d30d35b2.png)

**Comment by edgraham** [comment]
Hi Ruben,

I just went in and fixed that now. Apparently it didn't update on pip when I fixed it the first time. It shouldn't have affected the run itself though. That error runs because it is trying to close a file that was never opened!

Regards,
Elaina Graham

**Comment by rprops** [comment]
Hi Elaina,

Awesome, thank you for the quick response!

Best wishes,

Ruben
